CREATE TABLE urls (
                      id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                      "name" varchar(255) NOT NULL,
                      create_at timestamp NOT NULL,
                      CONSTRAINT urls_pk PRIMARY KEY (id),
                      CONSTRAINT urls_unique UNIQUE (name)
);

CREATE TABLE url_checks (
                            id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                            status_code int4 NULL,
                            h1 varchar(255) NULL,
                            title varchar(255) NULL,
                            description varchar(255) NULL,
                            created_at timestamp NULL,
                            url_id int4 NOT NULL,
                            CONSTRAINT checks_pk PRIMARY KEY (id),
                            CONSTRAINT url_checks_urls_fk FOREIGN KEY (url_id) REFERENCES urls(id)
);
