--
-- PostgreSQL database cluster dump
--

-- Started on 2024-09-12 11:55:17 +05

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE datadog;
ALTER ROLE datadog WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
CREATE ROLE db_urls_user;
ALTER ROLE db_urls_user WITH NOSUPERUSER INHERIT CREATEROLE CREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS;
CREATE ROLE primaryuser;
ALTER ROLE primaryuser WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN REPLICATION NOBYPASSRLS;

--
-- User Configurations
--


--
-- Role memberships
--

GRANT pg_monitor TO datadog WITH INHERIT TRUE GRANTED BY postgres;






--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3 (Debian 16.3-1.pgdg120+1)
-- Dumped by pg_dump version 16.2

-- Started on 2024-09-12 11:55:18 +05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Completed on 2024-09-12 11:55:25 +05

--
-- PostgreSQL database dump complete
--

--
-- Database "db_urls" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3 (Debian 16.3-1.pgdg120+1)
-- Dumped by pg_dump version 16.2

-- Started on 2024-09-12 11:55:25 +05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3367 (class 1262 OID 16389)
-- Name: db_urls; Type: DATABASE; Schema: -; Owner: db_urls_user
--

CREATE DATABASE db_urls WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.UTF8';


ALTER DATABASE db_urls OWNER TO db_urls_user;

\connect db_urls

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3368 (class 0 OID 0)
-- Name: db_urls; Type: DATABASE PROPERTIES; Schema: -; Owner: db_urls_user
--

ALTER DATABASE db_urls SET "TimeZone" TO 'utc';


\connect db_urls

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: db_urls_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO db_urls_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16404)
-- Name: url_checks; Type: TABLE; Schema: public; Owner: db_urls_user
--

CREATE TABLE public.url_checks (
    id integer NOT NULL,
    status_code integer,
    h1 character varying(255),
    title character varying(255),
    description character varying(255),
    created_at timestamp without time zone,
    url_id integer NOT NULL
);


ALTER TABLE public.url_checks OWNER TO db_urls_user;

--
-- TOC entry 217 (class 1259 OID 16403)
-- Name: checks_id_seq; Type: SEQUENCE; Schema: public; Owner: db_urls_user
--

ALTER TABLE public.url_checks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.checks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16400)
-- Name: urls; Type: TABLE; Schema: public; Owner: db_urls_user
--

CREATE TABLE public.urls (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    create_at timestamp without time zone NOT NULL
);


ALTER TABLE public.urls OWNER TO db_urls_user;

--
-- TOC entry 215 (class 1259 OID 16399)
-- Name: urls_id_seq; Type: SEQUENCE; Schema: public; Owner: db_urls_user
--

ALTER TABLE public.urls ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.urls_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3217 (class 2606 OID 16412)
-- Name: url_checks checks_pk; Type: CONSTRAINT; Schema: public; Owner: db_urls_user
--

ALTER TABLE ONLY public.url_checks
    ADD CONSTRAINT checks_pk PRIMARY KEY (id);


--
-- TOC entry 3213 (class 2606 OID 16410)
-- Name: urls urls_pk; Type: CONSTRAINT; Schema: public; Owner: db_urls_user
--

ALTER TABLE ONLY public.urls
    ADD CONSTRAINT urls_pk PRIMARY KEY (id);


--
-- TOC entry 3215 (class 2606 OID 16425)
-- Name: urls urls_unique; Type: CONSTRAINT; Schema: public; Owner: db_urls_user
--

ALTER TABLE ONLY public.urls
    ADD CONSTRAINT urls_unique UNIQUE (name);


--
-- TOC entry 3218 (class 2606 OID 16431)
-- Name: url_checks url_checks_urls_fk; Type: FK CONSTRAINT; Schema: public; Owner: db_urls_user
--

ALTER TABLE ONLY public.url_checks
    ADD CONSTRAINT url_checks_urls_fk FOREIGN KEY (url_id) REFERENCES public.urls(id);


--
-- TOC entry 2044 (class 826 OID 16391)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON SEQUENCES TO db_urls_user;


--
-- TOC entry 2046 (class 826 OID 16393)
-- Name: DEFAULT PRIVILEGES FOR TYPES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TYPES TO db_urls_user;


--
-- TOC entry 2045 (class 826 OID 16392)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON FUNCTIONS TO db_urls_user;


--
-- TOC entry 2043 (class 826 OID 16390)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO db_urls_user;


-- Completed on 2024-09-12 11:55:32 +05

--
-- PostgreSQL database dump complete
--

--
-- Database "postgres" dump
--

\connect postgres

