-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION db_urls_user;

-- DROP ROLE db_urls_user;

CREATE ROLE db_urls_user WITH
    NOSUPERUSER
    CREATEDB
    CREATEROLE
    INHERIT
    LOGIN
    NOREPLICATION
    NOBYPASSRLS
    CONNECTION LIMIT -1;

COMMENT ON SCHEMA public IS 'standard public schema';

-- DROP SEQUENCE public.checks_id_seq;

CREATE SEQUENCE public.checks_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.urls_id_seq;

CREATE SEQUENCE public.urls_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
	CACHE 1
	NO CYCLE;-- public.urls определение

-- Drop table

-- DROP TABLE public.urls;

CREATE TABLE public.urls (
                             id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                             "name" varchar(255) NOT NULL,
                             create_at timestamp NOT NULL,
                             CONSTRAINT urls_pk PRIMARY KEY (id),
                             CONSTRAINT urls_unique UNIQUE (name)
);


-- public.url_checks определение

-- Drop table

-- DROP TABLE public.url_checks;

CREATE TABLE public.url_checks (
                                   id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                   status_code int4 NULL,
                                   h1 varchar(255) NULL,
                                   title varchar(255) NULL,
                                   description varchar(255) NULL,
                                   created_at timestamp NULL,
                                   url_id int4 NOT NULL,
                                   CONSTRAINT checks_pk PRIMARY KEY (id),
                                   CONSTRAINT url_checks_urls_fk FOREIGN KEY (url_id) REFERENCES public.urls(id)
);
