-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION db_urls_user;
-- public.urls определение

-- Drop table

-- DROP TABLE public.urls;

CREATE TABLE public.urls (
                             id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                             "name" varchar(255) NOT NULL,
                             create_at timestamp NULL,
                             CONSTRAINT urls_pk PRIMARY KEY (id),
                             CONSTRAINT urls_unique UNIQUE (name)
);


-- public.checks определение

-- Drop table

-- DROP TABLE public.checks;

CREATE TABLE public.checks (
                               id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                               code_response int4 NULL,
                               h1_text varchar(255) NULL,
                               title_text varchar(255) NULL,
                               description_text varchar(255) NULL,
                               create_at timestamp NULL,
                               url_id int4 NOT NULL,
                               CONSTRAINT checks_pk PRIMARY KEY (id),
                               CONSTRAINT checks_urls_fk FOREIGN KEY (id) REFERENCES public.urls(id)
);
