--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3 (Debian 16.3-1.pgdg120+1)
-- Dumped by pg_dump version 16.2

-- Started on 2024-09-11 14:27:44 +05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE db_urls;
--
-- TOC entry 3371 (class 1262 OID 16389)
-- Name: db_urls; Type: DATABASE; Schema: -; Owner: db_urls_user
--

CREATE DATABASE db_urls WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.UTF8';


ALTER DATABASE db_urls OWNER TO db_urls_user;

\connect db_urls

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3372 (class 0 OID 0)
-- Name: db_urls; Type: DATABASE PROPERTIES; Schema: -; Owner: db_urls_user
--

ALTER DATABASE db_urls SET "TimeZone" TO 'utc';


\connect db_urls

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: db_urls_user
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO db_urls_user;

--
-- TOC entry 3373 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: db_urls_user
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16404)
-- Name: url_checks; Type: TABLE; Schema: public; Owner: db_urls_user
--

CREATE TABLE public.url_checks (
    id integer NOT NULL,
    status_code integer,
    h1 character varying(255),
    title character varying(255),
    description character varying(255),
    created_at timestamp without time zone,
    url_id integer NOT NULL
);


ALTER TABLE public.url_checks OWNER TO db_urls_user;

--
-- TOC entry 217 (class 1259 OID 16403)
-- Name: checks_id_seq; Type: SEQUENCE; Schema: public; Owner: db_urls_user
--

ALTER TABLE public.url_checks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.checks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16400)
-- Name: urls; Type: TABLE; Schema: public; Owner: db_urls_user
--

CREATE TABLE public.urls (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    create_at timestamp without time zone NOT NULL
);


ALTER TABLE public.urls OWNER TO db_urls_user;

--
-- TOC entry 215 (class 1259 OID 16399)
-- Name: urls_id_seq; Type: SEQUENCE; Schema: public; Owner: db_urls_user
--

ALTER TABLE public.urls ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.urls_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3365 (class 0 OID 16404)
-- Dependencies: 218
-- Data for Name: url_checks; Type: TABLE DATA; Schema: public; Owner: db_urls_user
--

INSERT INTO public.url_checks VALUES (4, NULL, NULL, NULL, NULL, '2024-09-11 08:09:25', 17);
INSERT INTO public.url_checks VALUES (5, NULL, NULL, NULL, NULL, '2024-09-11 08:09:27', 17);
INSERT INTO public.url_checks VALUES (6, NULL, NULL, NULL, NULL, '2024-09-11 08:09:38', 17);
INSERT INTO public.url_checks VALUES (7, NULL, NULL, NULL, NULL, '2024-09-11 08:09:13', 17);
INSERT INTO public.url_checks VALUES (8, NULL, NULL, NULL, NULL, '2024-09-11 08:09:46', 17);


--
-- TOC entry 3363 (class 0 OID 16400)
-- Dependencies: 216
-- Data for Name: urls; Type: TABLE DATA; Schema: public; Owner: db_urls_user
--

INSERT INTO public.urls VALUES (17, 'https://ya.ru', '2024-09-11 05:09:40');
INSERT INTO public.urls VALUES (18, 'https://github.com', '2024-09-11 05:09:05');
INSERT INTO public.urls VALUES (19, 'https://www.instagram.com', '2024-09-11 08:09:15');


--
-- TOC entry 3374 (class 0 OID 0)
-- Dependencies: 217
-- Name: checks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: db_urls_user
--

SELECT pg_catalog.setval('public.checks_id_seq', 8, true);


--
-- TOC entry 3375 (class 0 OID 0)
-- Dependencies: 215
-- Name: urls_id_seq; Type: SEQUENCE SET; Schema: public; Owner: db_urls_user
--

SELECT pg_catalog.setval('public.urls_id_seq', 19, true);


--
-- TOC entry 3217 (class 2606 OID 16412)
-- Name: url_checks checks_pk; Type: CONSTRAINT; Schema: public; Owner: db_urls_user
--

ALTER TABLE ONLY public.url_checks
    ADD CONSTRAINT checks_pk PRIMARY KEY (id);


--
-- TOC entry 3213 (class 2606 OID 16410)
-- Name: urls urls_pk; Type: CONSTRAINT; Schema: public; Owner: db_urls_user
--

ALTER TABLE ONLY public.urls
    ADD CONSTRAINT urls_pk PRIMARY KEY (id);


--
-- TOC entry 3215 (class 2606 OID 16425)
-- Name: urls urls_unique; Type: CONSTRAINT; Schema: public; Owner: db_urls_user
--

ALTER TABLE ONLY public.urls
    ADD CONSTRAINT urls_unique UNIQUE (name);


--
-- TOC entry 3218 (class 2606 OID 16431)
-- Name: url_checks url_checks_urls_fk; Type: FK CONSTRAINT; Schema: public; Owner: db_urls_user
--

ALTER TABLE ONLY public.url_checks
    ADD CONSTRAINT url_checks_urls_fk FOREIGN KEY (url_id) REFERENCES public.urls(id);


-- Completed on 2024-09-11 14:27:54 +05

--
-- PostgreSQL database dump complete
--

